### ISSUE TITLE
Modal 구현

### ISSUE THREAD

**Issue by SeonHwan-Kim** [Soongsil-Developers/terrace-web#22]
## 설명
- room 버튼 클릭 시 Modal 창 뜨도록 하기

## To-do

- [x] room 버튼 구현
- [x] modal 창 생성
- [x] modal 창에서 예약 버튼 클릭 시 room 버튼 색상 변경
- [x] 예약 중인 room 버튼 클릭 시 modal 창 내용, 버튼 변경
